### ISSUE TITLE
Allow `conda env create` and `conda env update` to add a channel to an environment.

### ISSUE THREAD

**Issue by amfarrell** [conda/conda-env#61] opened 2015-02-20 21:44 UTC
I can run `conda config --file environment.yml --add channels http://kts02:8000` to add a custom channel to an environment.yml file. When I run `conda env create --name foo --file environment.yml` using that file, conda env should see the 
```yml
   channels:
     - http://kts02:8000
     - defaults
```
in environment.yml and should add that channel to the list of channels that this environment can install from. That way, if a client has an internal conda channel, when I create a project that draws on packages located only in that channel, I can create an environment.yml for that project that others can use to create their environment and can `conda install` packages from that channel without having to remember the url for the custom channel.

**Comment by tswicegood** [comment] 2015-02-20 23:31
Using `conda config` is the wrong tool here.

Other than that, though, I'm not sure what you're asking for.  There's already a `channels` attribute for `environment.yml` files -- I was going to link to an example showing that behavior, but I apparently don't have any.  At any rate, `channels` support has been in conda-env for awhile (at least v1.3, but I think it was there before that).

Here's an example from the internal flask template:

```yaml
name: design
channels:
  - javascript
  - continuumio
dependencies:
  - python<=3
  - flask
  - bower
  - gulp
  - continuum-flask
```

**Comment by amfarrell** [comment] 2015-02-22 03:32
I was actually confused about a part of this. Running `conda env create --file env.yml` on a file like this works, however, if I run `conda install mocha`, I get "Error: No packages found in current osx-64 channels matching: mocha", despite the mocha package for osx being in that channel. This means that the environment itself does not have a channel attached, it just builds itself from the given channels on creation time.

**Comment by amfarrell** [comment] 2015-02-22 03:35
Unrelatedly, if I run `conda env create --file env.yml`, on that a file with those actual contents I get the error "Could not find some dependencies for bower: iojs"

**Comment by tswicegood** [comment] 2015-02-25 23:59
@amfarrell try it again.  There was an issue with the `iojs` package.

**Comment by mattions** [comment] 2015-03-27 11:31
When re-exporting an environment the information about the channels get lost and they shouldn't
Can we change `conda env export` to check if there is an environment and combine the channels information?

**Comment by tswicegood** [comment] 2015-04-01 18:08
@mattions that's reasonable.  That said, updating `conda env export` to be channel aware would solve the problem as any packages that were installed from channels would trigger adding channels.  

I think there's a slightly different path here in that you export and then modify your channels you want those modifications to stay in place.  Do you see a case where you'd want channels added that might or might not actually be what was used to install?

**Comment by mattions** [comment] 2015-04-02 09:02
Hi,

my usercase would be to keep the channels in the environment, and to not add new one.
The user should be in charge of that, because adding other channels, and the order of the channels, could change which package is picked by conda (it resolves dependencies in a first found first used fashion).

This is my workflow:

my environment:
```
name: moka_env
channels:
    - mattions
    - Judowill
    - cgat
dependencies:
- bedtools=2.21.0=0
- binstar=0.10.1=py27_1
- cairo=1.12.18=0
- clyent=0.3.2=py27_0
- cython=0.21.2=py27_0
- dateutil=2.4.1=py27_0
- ...
```

I update a packages
I would like to do
`conda env export > environment.yml`

Where the channel block, if exists, should be kept verbatim and just added to the output.

What do you think?

**Comment by tswicegood** [comment] 2015-04-02 17:51
@mattions that makes sense.  There's another scenario that I'd like to support as well, though I think these are two separate things.

* User edits `environment.yml` file to add channels, those are given priority
* User installs a new package with `conda install -c some-new-channel some-package` and the next export now contains this channel.

**Comment by mattions** [comment] 2015-04-02 18:27
Sure, I honestly think first option is what I really need, the second one
would be a nice top up.

**Comment by kpurdon** [comment] 2015-05-06 16:01
+1 for both of those options, but at the minimum not clobbering existing channels when doing an export to update dependencies.

**Comment by Juanlu001** [comment] 2015-06-04 20:24
I was about to report a new issue regarding the `conda env export` behavior, but @mattions already expressed my same concerns in https://github.com/conda/conda-env/issues/61#issuecomment-86906881. When you export an environment which contains packages coming from non-official channels, that information gets lost and another user cannot use the resulting `environment.yml` to reproduce your environment.

**Comment by malev** [comment] 2015-08-10 23:34
I'm moving this conversations into #145. Closing now

**Closed by malev** 2015-08-10 23:34 UTC
Labels: enhancement
