### ISSUE TITLE
Conda-create downgrades Python 3 to Python 2

### ISSUE THREAD

**Issue by frol** [conda/conda-env#158] opened 2015-08-13 10:49 UTC
I have a MIniconda3 setup with Python 3.4.3 and when I try to create a new conda environment with Python it wants to install Python 2.7.10 for some weird reason:

```
[root@3cea1eb9f5b8 /]# python
Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

[root@3cea1eb9f5b8 /]# conda create -p /tmp/env python
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /tmp/env:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.10              |                0        13.5 MB
    setuptools-18.0.1          |           py27_0         341 KB
    wheel-0.24.0               |           py27_0          75 KB
    pip-7.1.0                  |           py27_1         1.4 MB
    ------------------------------------------------------------
                                           Total:        15.2 MB
```

It used to work correctly a week ago. I tried to downgrade `conda` and `conda-env` packages with no luck. My guess is that something wrong happened with continuum.io/free/pkgs index.

Do you have any ideas on what have happened?

**Comment by frol** [comment] 2015-08-13 11:08
Here is a Dockerfile where I can reproduce the issue:

```Dockerfile
FROM centos:6

RUN yum -y install \
        glibc-devel \
        make \
        libxml2-devel \
        which patch \
        tar bzip2 gzip unzip && \
    yum clean all

ENV PATH="/usr/local/miniconda/bin:$PATH"
RUN echo "PATH='$PATH'" >> /etc/environment

RUN cd /tmp && \
    curl -L "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -o Miniconda.sh && \
    bash Miniconda.sh -b -f -p "/usr/local/miniconda" && \
    rm Miniconda.sh && \
    conda install --yes conda-build anaconda-client && \
    conda clean --packages --tarballs --yes
```

**Comment by frol** [comment] 2015-08-13 12:35
@asmeurer Is this also the instance of https://github.com/conda/conda/issues/1338

**Comment by frol** [comment] 2015-08-13 13:04
I digged into our Jenkins logs and discovered that it used to work YESTERDAY.

It worked just fine at Aug 12, 2015 10:47 AM PDT and 20 minutes later, at Aug 12, 2015 11:06 AM PDT, it went using Python 2.7.10 instead of Python 3.4.3!

**Comment by malev** [comment] 2015-08-13 15:51
@frol at first glance looks like you should be running:
`conda create -p /tmp/env` (remove the python)
Could you try that please?

**Comment by frol** [comment] 2015-08-13 16:35
@malev It never worked for me this way because I don't have anything in condarc by default:

```
[root@77a187e7142d /]# conda create -p /tmp/env
Error: too few arguments, must supply command line package specs or --file

You can specify one or more default packages to install when creating
an environment.  Doing so allows you to call conda create without
explicitly providing any package names.

To set the provided packages, call conda config like this:

    conda config --add create_default_packages PACKAGE_NAME
```

**Comment by frol** [comment] 2015-08-13 16:37
@malev If I add python to `create_default_packages`, it still tries to install Python 2.

**Comment by malev** [comment] 2015-08-13 16:42
conda create -p /tmp/env python=3.4

**Comment by malev** [comment] 2015-08-13 22:06
@frol this is not a bug from conda-env. I'm gonna close this issue

**Comment by frol** [comment] 2015-08-14 07:15
@malev `conda install python`, and `conda update python`, and `conda update --all` don't downgrade `python`. It used to work without setting explicit version just two days ago. However, I have noticed that `conda create` doesn't seem to be a part of conda-env, which is unexpected... I will put this bug in conda project then.

**Comment by malev** [comment] 2015-08-14 17:50
yes! `conda create` belongs to `conda`.

**Closed** 2015-08-14 17:50 UTC
